# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/net_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/net_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/net_lib/CMakeFiles /root/net_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/net_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named net_lib

# Build rule for target.
net_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 net_lib
.PHONY : net_lib

# fast build rule for target.
net_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/build
.PHONY : net_lib/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_Inet

# Build rule for target.
test_Inet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_Inet
.PHONY : test_Inet

# fast build rule for target.
test_Inet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Inet.dir/build.make CMakeFiles/test_Inet.dir/build
.PHONY : test_Inet/fast

Src/Base/Date.o: Src/Base/Date.cpp.o
.PHONY : Src/Base/Date.o

# target to build an object file
Src/Base/Date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Date.cpp.o
.PHONY : Src/Base/Date.cpp.o

Src/Base/Date.i: Src/Base/Date.cpp.i
.PHONY : Src/Base/Date.i

# target to preprocess a source file
Src/Base/Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Date.cpp.i
.PHONY : Src/Base/Date.cpp.i

Src/Base/Date.s: Src/Base/Date.cpp.s
.PHONY : Src/Base/Date.s

# target to generate assembly for a file
Src/Base/Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Date.cpp.s
.PHONY : Src/Base/Date.cpp.s

Src/Base/Logger.o: Src/Base/Logger.cc.o
.PHONY : Src/Base/Logger.o

# target to build an object file
Src/Base/Logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Logger.cc.o
.PHONY : Src/Base/Logger.cc.o

Src/Base/Logger.i: Src/Base/Logger.cc.i
.PHONY : Src/Base/Logger.i

# target to preprocess a source file
Src/Base/Logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Logger.cc.i
.PHONY : Src/Base/Logger.cc.i

Src/Base/Logger.s: Src/Base/Logger.cc.s
.PHONY : Src/Base/Logger.s

# target to generate assembly for a file
Src/Base/Logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Logger.cc.s
.PHONY : Src/Base/Logger.cc.s

Src/Base/Thread.o: Src/Base/Thread.cpp.o
.PHONY : Src/Base/Thread.o

# target to build an object file
Src/Base/Thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Thread.cpp.o
.PHONY : Src/Base/Thread.cpp.o

Src/Base/Thread.i: Src/Base/Thread.cpp.i
.PHONY : Src/Base/Thread.i

# target to preprocess a source file
Src/Base/Thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Thread.cpp.i
.PHONY : Src/Base/Thread.cpp.i

Src/Base/Thread.s: Src/Base/Thread.cpp.s
.PHONY : Src/Base/Thread.s

# target to generate assembly for a file
Src/Base/Thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Thread.cpp.s
.PHONY : Src/Base/Thread.cpp.s

Src/Base/Timestamp.o: Src/Base/Timestamp.cpp.o
.PHONY : Src/Base/Timestamp.o

# target to build an object file
Src/Base/Timestamp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Timestamp.cpp.o
.PHONY : Src/Base/Timestamp.cpp.o

Src/Base/Timestamp.i: Src/Base/Timestamp.cpp.i
.PHONY : Src/Base/Timestamp.i

# target to preprocess a source file
Src/Base/Timestamp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Timestamp.cpp.i
.PHONY : Src/Base/Timestamp.cpp.i

Src/Base/Timestamp.s: Src/Base/Timestamp.cpp.s
.PHONY : Src/Base/Timestamp.s

# target to generate assembly for a file
Src/Base/Timestamp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/Base/Timestamp.cpp.s
.PHONY : Src/Base/Timestamp.cpp.s

Src/net/Acceptor.o: Src/net/Acceptor.cpp.o
.PHONY : Src/net/Acceptor.o

# target to build an object file
Src/net/Acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Acceptor.cpp.o
.PHONY : Src/net/Acceptor.cpp.o

Src/net/Acceptor.i: Src/net/Acceptor.cpp.i
.PHONY : Src/net/Acceptor.i

# target to preprocess a source file
Src/net/Acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Acceptor.cpp.i
.PHONY : Src/net/Acceptor.cpp.i

Src/net/Acceptor.s: Src/net/Acceptor.cpp.s
.PHONY : Src/net/Acceptor.s

# target to generate assembly for a file
Src/net/Acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Acceptor.cpp.s
.PHONY : Src/net/Acceptor.cpp.s

Src/net/Buffer.o: Src/net/Buffer.cpp.o
.PHONY : Src/net/Buffer.o

# target to build an object file
Src/net/Buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Buffer.cpp.o
.PHONY : Src/net/Buffer.cpp.o

Src/net/Buffer.i: Src/net/Buffer.cpp.i
.PHONY : Src/net/Buffer.i

# target to preprocess a source file
Src/net/Buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Buffer.cpp.i
.PHONY : Src/net/Buffer.cpp.i

Src/net/Buffer.s: Src/net/Buffer.cpp.s
.PHONY : Src/net/Buffer.s

# target to generate assembly for a file
Src/net/Buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Buffer.cpp.s
.PHONY : Src/net/Buffer.cpp.s

Src/net/Channel.o: Src/net/Channel.cpp.o
.PHONY : Src/net/Channel.o

# target to build an object file
Src/net/Channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Channel.cpp.o
.PHONY : Src/net/Channel.cpp.o

Src/net/Channel.i: Src/net/Channel.cpp.i
.PHONY : Src/net/Channel.i

# target to preprocess a source file
Src/net/Channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Channel.cpp.i
.PHONY : Src/net/Channel.cpp.i

Src/net/Channel.s: Src/net/Channel.cpp.s
.PHONY : Src/net/Channel.s

# target to generate assembly for a file
Src/net/Channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Channel.cpp.s
.PHONY : Src/net/Channel.cpp.s

Src/net/CurrentThread.o: Src/net/CurrentThread.cpp.o
.PHONY : Src/net/CurrentThread.o

# target to build an object file
Src/net/CurrentThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/CurrentThread.cpp.o
.PHONY : Src/net/CurrentThread.cpp.o

Src/net/CurrentThread.i: Src/net/CurrentThread.cpp.i
.PHONY : Src/net/CurrentThread.i

# target to preprocess a source file
Src/net/CurrentThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/CurrentThread.cpp.i
.PHONY : Src/net/CurrentThread.cpp.i

Src/net/CurrentThread.s: Src/net/CurrentThread.cpp.s
.PHONY : Src/net/CurrentThread.s

# target to generate assembly for a file
Src/net/CurrentThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/CurrentThread.cpp.s
.PHONY : Src/net/CurrentThread.cpp.s

Src/net/DefaultPoller.o: Src/net/DefaultPoller.cpp.o
.PHONY : Src/net/DefaultPoller.o

# target to build an object file
Src/net/DefaultPoller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/DefaultPoller.cpp.o
.PHONY : Src/net/DefaultPoller.cpp.o

Src/net/DefaultPoller.i: Src/net/DefaultPoller.cpp.i
.PHONY : Src/net/DefaultPoller.i

# target to preprocess a source file
Src/net/DefaultPoller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/DefaultPoller.cpp.i
.PHONY : Src/net/DefaultPoller.cpp.i

Src/net/DefaultPoller.s: Src/net/DefaultPoller.cpp.s
.PHONY : Src/net/DefaultPoller.s

# target to generate assembly for a file
Src/net/DefaultPoller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/DefaultPoller.cpp.s
.PHONY : Src/net/DefaultPoller.cpp.s

Src/net/EventLoop.o: Src/net/EventLoop.cpp.o
.PHONY : Src/net/EventLoop.o

# target to build an object file
Src/net/EventLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoop.cpp.o
.PHONY : Src/net/EventLoop.cpp.o

Src/net/EventLoop.i: Src/net/EventLoop.cpp.i
.PHONY : Src/net/EventLoop.i

# target to preprocess a source file
Src/net/EventLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoop.cpp.i
.PHONY : Src/net/EventLoop.cpp.i

Src/net/EventLoop.s: Src/net/EventLoop.cpp.s
.PHONY : Src/net/EventLoop.s

# target to generate assembly for a file
Src/net/EventLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoop.cpp.s
.PHONY : Src/net/EventLoop.cpp.s

Src/net/EventLoopThread.o: Src/net/EventLoopThread.cpp.o
.PHONY : Src/net/EventLoopThread.o

# target to build an object file
Src/net/EventLoopThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThread.cpp.o
.PHONY : Src/net/EventLoopThread.cpp.o

Src/net/EventLoopThread.i: Src/net/EventLoopThread.cpp.i
.PHONY : Src/net/EventLoopThread.i

# target to preprocess a source file
Src/net/EventLoopThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThread.cpp.i
.PHONY : Src/net/EventLoopThread.cpp.i

Src/net/EventLoopThread.s: Src/net/EventLoopThread.cpp.s
.PHONY : Src/net/EventLoopThread.s

# target to generate assembly for a file
Src/net/EventLoopThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThread.cpp.s
.PHONY : Src/net/EventLoopThread.cpp.s

Src/net/EventLoopThreadPool.o: Src/net/EventLoopThreadPool.cpp.o
.PHONY : Src/net/EventLoopThreadPool.o

# target to build an object file
Src/net/EventLoopThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThreadPool.cpp.o
.PHONY : Src/net/EventLoopThreadPool.cpp.o

Src/net/EventLoopThreadPool.i: Src/net/EventLoopThreadPool.cpp.i
.PHONY : Src/net/EventLoopThreadPool.i

# target to preprocess a source file
Src/net/EventLoopThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThreadPool.cpp.i
.PHONY : Src/net/EventLoopThreadPool.cpp.i

Src/net/EventLoopThreadPool.s: Src/net/EventLoopThreadPool.cpp.s
.PHONY : Src/net/EventLoopThreadPool.s

# target to generate assembly for a file
Src/net/EventLoopThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/EventLoopThreadPool.cpp.s
.PHONY : Src/net/EventLoopThreadPool.cpp.s

Src/net/InetAddress.o: Src/net/InetAddress.cpp.o
.PHONY : Src/net/InetAddress.o

# target to build an object file
Src/net/InetAddress.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/InetAddress.cpp.o
.PHONY : Src/net/InetAddress.cpp.o

Src/net/InetAddress.i: Src/net/InetAddress.cpp.i
.PHONY : Src/net/InetAddress.i

# target to preprocess a source file
Src/net/InetAddress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/InetAddress.cpp.i
.PHONY : Src/net/InetAddress.cpp.i

Src/net/InetAddress.s: Src/net/InetAddress.cpp.s
.PHONY : Src/net/InetAddress.s

# target to generate assembly for a file
Src/net/InetAddress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/InetAddress.cpp.s
.PHONY : Src/net/InetAddress.cpp.s

Src/net/Poller/EpollPoller.o: Src/net/Poller/EpollPoller.cpp.o
.PHONY : Src/net/Poller/EpollPoller.o

# target to build an object file
Src/net/Poller/EpollPoller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/EpollPoller.cpp.o
.PHONY : Src/net/Poller/EpollPoller.cpp.o

Src/net/Poller/EpollPoller.i: Src/net/Poller/EpollPoller.cpp.i
.PHONY : Src/net/Poller/EpollPoller.i

# target to preprocess a source file
Src/net/Poller/EpollPoller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/EpollPoller.cpp.i
.PHONY : Src/net/Poller/EpollPoller.cpp.i

Src/net/Poller/EpollPoller.s: Src/net/Poller/EpollPoller.cpp.s
.PHONY : Src/net/Poller/EpollPoller.s

# target to generate assembly for a file
Src/net/Poller/EpollPoller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/EpollPoller.cpp.s
.PHONY : Src/net/Poller/EpollPoller.cpp.s

Src/net/Poller/Poller.o: Src/net/Poller/Poller.cpp.o
.PHONY : Src/net/Poller/Poller.o

# target to build an object file
Src/net/Poller/Poller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/Poller.cpp.o
.PHONY : Src/net/Poller/Poller.cpp.o

Src/net/Poller/Poller.i: Src/net/Poller/Poller.cpp.i
.PHONY : Src/net/Poller/Poller.i

# target to preprocess a source file
Src/net/Poller/Poller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/Poller.cpp.i
.PHONY : Src/net/Poller/Poller.cpp.i

Src/net/Poller/Poller.s: Src/net/Poller/Poller.cpp.s
.PHONY : Src/net/Poller/Poller.s

# target to generate assembly for a file
Src/net/Poller/Poller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Poller/Poller.cpp.s
.PHONY : Src/net/Poller/Poller.cpp.s

Src/net/Socket.o: Src/net/Socket.cpp.o
.PHONY : Src/net/Socket.o

# target to build an object file
Src/net/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Socket.cpp.o
.PHONY : Src/net/Socket.cpp.o

Src/net/Socket.i: Src/net/Socket.cpp.i
.PHONY : Src/net/Socket.i

# target to preprocess a source file
Src/net/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Socket.cpp.i
.PHONY : Src/net/Socket.cpp.i

Src/net/Socket.s: Src/net/Socket.cpp.s
.PHONY : Src/net/Socket.s

# target to generate assembly for a file
Src/net/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/Socket.cpp.s
.PHONY : Src/net/Socket.cpp.s

Src/net/TCPConnection.o: Src/net/TCPConnection.cpp.o
.PHONY : Src/net/TCPConnection.o

# target to build an object file
Src/net/TCPConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPConnection.cpp.o
.PHONY : Src/net/TCPConnection.cpp.o

Src/net/TCPConnection.i: Src/net/TCPConnection.cpp.i
.PHONY : Src/net/TCPConnection.i

# target to preprocess a source file
Src/net/TCPConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPConnection.cpp.i
.PHONY : Src/net/TCPConnection.cpp.i

Src/net/TCPConnection.s: Src/net/TCPConnection.cpp.s
.PHONY : Src/net/TCPConnection.s

# target to generate assembly for a file
Src/net/TCPConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPConnection.cpp.s
.PHONY : Src/net/TCPConnection.cpp.s

Src/net/TCPServer.o: Src/net/TCPServer.cpp.o
.PHONY : Src/net/TCPServer.o

# target to build an object file
Src/net/TCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPServer.cpp.o
.PHONY : Src/net/TCPServer.cpp.o

Src/net/TCPServer.i: Src/net/TCPServer.cpp.i
.PHONY : Src/net/TCPServer.i

# target to preprocess a source file
Src/net/TCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPServer.cpp.i
.PHONY : Src/net/TCPServer.cpp.i

Src/net/TCPServer.s: Src/net/TCPServer.cpp.s
.PHONY : Src/net/TCPServer.s

# target to generate assembly for a file
Src/net/TCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/Src/net/TCPServer.cpp.s
.PHONY : Src/net/TCPServer.cpp.s

Src/test/Inet_test.o: Src/test/Inet_test.cpp.o
.PHONY : Src/test/Inet_test.o

# target to build an object file
Src/test/Inet_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Inet.dir/build.make CMakeFiles/test_Inet.dir/Src/test/Inet_test.cpp.o
.PHONY : Src/test/Inet_test.cpp.o

Src/test/Inet_test.i: Src/test/Inet_test.cpp.i
.PHONY : Src/test/Inet_test.i

# target to preprocess a source file
Src/test/Inet_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Inet.dir/build.make CMakeFiles/test_Inet.dir/Src/test/Inet_test.cpp.i
.PHONY : Src/test/Inet_test.cpp.i

Src/test/Inet_test.s: Src/test/Inet_test.cpp.s
.PHONY : Src/test/Inet_test.s

# target to generate assembly for a file
Src/test/Inet_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_Inet.dir/build.make CMakeFiles/test_Inet.dir/Src/test/Inet_test.cpp.s
.PHONY : Src/test/Inet_test.cpp.s

Src/test/Logger_test.o: Src/test/Logger_test.cpp.o
.PHONY : Src/test/Logger_test.o

# target to build an object file
Src/test/Logger_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Src/test/Logger_test.cpp.o
.PHONY : Src/test/Logger_test.cpp.o

Src/test/Logger_test.i: Src/test/Logger_test.cpp.i
.PHONY : Src/test/Logger_test.i

# target to preprocess a source file
Src/test/Logger_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Src/test/Logger_test.cpp.i
.PHONY : Src/test/Logger_test.cpp.i

Src/test/Logger_test.s: Src/test/Logger_test.cpp.s
.PHONY : Src/test/Logger_test.s

# target to generate assembly for a file
Src/test/Logger_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Src/test/Logger_test.cpp.s
.PHONY : Src/test/Logger_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... net_lib"
	@echo "... test"
	@echo "... test_Inet"
	@echo "... Src/Base/Date.o"
	@echo "... Src/Base/Date.i"
	@echo "... Src/Base/Date.s"
	@echo "... Src/Base/Logger.o"
	@echo "... Src/Base/Logger.i"
	@echo "... Src/Base/Logger.s"
	@echo "... Src/Base/Thread.o"
	@echo "... Src/Base/Thread.i"
	@echo "... Src/Base/Thread.s"
	@echo "... Src/Base/Timestamp.o"
	@echo "... Src/Base/Timestamp.i"
	@echo "... Src/Base/Timestamp.s"
	@echo "... Src/net/Acceptor.o"
	@echo "... Src/net/Acceptor.i"
	@echo "... Src/net/Acceptor.s"
	@echo "... Src/net/Buffer.o"
	@echo "... Src/net/Buffer.i"
	@echo "... Src/net/Buffer.s"
	@echo "... Src/net/Channel.o"
	@echo "... Src/net/Channel.i"
	@echo "... Src/net/Channel.s"
	@echo "... Src/net/CurrentThread.o"
	@echo "... Src/net/CurrentThread.i"
	@echo "... Src/net/CurrentThread.s"
	@echo "... Src/net/DefaultPoller.o"
	@echo "... Src/net/DefaultPoller.i"
	@echo "... Src/net/DefaultPoller.s"
	@echo "... Src/net/EventLoop.o"
	@echo "... Src/net/EventLoop.i"
	@echo "... Src/net/EventLoop.s"
	@echo "... Src/net/EventLoopThread.o"
	@echo "... Src/net/EventLoopThread.i"
	@echo "... Src/net/EventLoopThread.s"
	@echo "... Src/net/EventLoopThreadPool.o"
	@echo "... Src/net/EventLoopThreadPool.i"
	@echo "... Src/net/EventLoopThreadPool.s"
	@echo "... Src/net/InetAddress.o"
	@echo "... Src/net/InetAddress.i"
	@echo "... Src/net/InetAddress.s"
	@echo "... Src/net/Poller/EpollPoller.o"
	@echo "... Src/net/Poller/EpollPoller.i"
	@echo "... Src/net/Poller/EpollPoller.s"
	@echo "... Src/net/Poller/Poller.o"
	@echo "... Src/net/Poller/Poller.i"
	@echo "... Src/net/Poller/Poller.s"
	@echo "... Src/net/Socket.o"
	@echo "... Src/net/Socket.i"
	@echo "... Src/net/Socket.s"
	@echo "... Src/net/TCPConnection.o"
	@echo "... Src/net/TCPConnection.i"
	@echo "... Src/net/TCPConnection.s"
	@echo "... Src/net/TCPServer.o"
	@echo "... Src/net/TCPServer.i"
	@echo "... Src/net/TCPServer.s"
	@echo "... Src/test/Inet_test.o"
	@echo "... Src/test/Inet_test.i"
	@echo "... Src/test/Inet_test.s"
	@echo "... Src/test/Logger_test.o"
	@echo "... Src/test/Logger_test.i"
	@echo "... Src/test/Logger_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

